import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const OutfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vetnest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OutfitFont.className} bg-amber-300`}>{children}</body>
    </html>
  );
}
